Repository squareboat/nest-mailman, pull requests merged in 2020-10, with the labels that each got.

#5 feat: Separating mailables and transporter methods
  lib/MailMessage.ts
  lib/constants.ts
  lib/index.ts
  lib/interfaces/options.ts
  lib/mailman.ts
  lib/service.ts
  lib/views/mail/generic.hbs
Labels: hacktoberfest

#6 Refactored MailMessage class and Other Changes
  lib/constants.ts
  lib/index.ts
  lib/interfaces/options.ts
  lib/mailman.ts
  lib/message.ts
  lib/queue/consumer.ts
  lib/service.ts
  lib/views/mail/generic.ts
  lib/views/mail/index.ts
Labels: hacktoberfest, hacktoberfest-accepted

#9 fix: Mail builder generic styles
  lib/views/mail/generic.ts
Labels: hacktoberfest-accepted
